---
 - name: Install nginx
   yum: name=nginx state=present

 - name: Copy nginx configuration for wordpress
   template: src=default.conf dest=/etc/nginx/conf.d/default.conf

 - name: Copy nginx configuration for wordpress
   template: src=nginx.conf dest=/etc/nginx/nginx.conf

 - name: Generate Cert
   command: openssl req -x509 -nodes -days 365 -batch -newkey rsa:2048 -keyout /etc/nginx/cert.key -out /etc/nginx/cert.crt
   notify: restart nginx

 - name: Add nginx service to autostart
   command: chkconfig --level 345 nginx on