---
- name: Install WordPress, MySQL, Nginx, PHP-FPM, Apache, phpmyadmin
  hosts: all

  roles:
    - common
    - mysql
    - httpd
    - phpmyadmin
    - wordpress
    - nginx
    - backup
    - vsftpd

