---
 - name: Install Apache
   yum: name=httpd state=present

 - name: Copy httpd configuration for back-end
   template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
   notify: restart httpd

 - name: Apache to autostart
   command: chkconfig --level 2345 httpd on